services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=jobsity
      - SERVER_PORT=3000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_data:/data/db

volumes:
  mongodb_data:
